---
abstract: 'Installs WWW::Mechanize with dependencies'
author:
  - 'Kevin W. Henwood <Khen1950fx@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Mechanistic
no_index:
  directory:
    - inc
    - t
requires:
  Algorithm::Diff: 0
  App::PodLinkCheck::ParseLinks: 0
  Archive::Any: 0
  Archive::Any::Lite: 0
  Archive::Tar: 0
  Archive::Zip: 0
  Array::Diff: 0
  Attribute::Handlers: 0
  AutoLoader: 0
  B::Hooks::EndOfScope: 0
  B::Hooks::OP::Check: 0
  B::Keywords: 0
  CGI: 0
  CPAN::DistnameInfo: 0
  CPAN::Meta: 0
  CPAN::Meta::Requirements: 0
  CPAN::Meta::YAML: 0
  Capture::Tiny: 0
  Carp: 0
  Class::Accessor: 0
  Class::Accessor::Fast: 0
  Class::Accessor::Fast::XS: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 0
  Class::Iterator: 0
  Class::Load: 0
  Class::Load::XS: 0
  Class::Singleton: 0
  Class::Tiny: 0
  Class::XSAccessor: 0
  Clone: 0
  Compress::Raw::Bzip2: 0
  Compress::Raw::Zlib: 0
  Compress::Zlib: 0
  Config::Tiny: 0
  Crypt::SSLeay: 0
  Data::Dump: 0
  Data::Dumper: 0
  Data::OptList: 0
  Data::Section: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::W3CDTF: 0
  DateTime::Locale: 0
  DateTime::TimeZone: 0
  Devel::Declare: 0
  Devel::GlobalDestruction: 0
  Devel::PPPort: 0
  Devel::StackTrace: 0
  Devel::Symdump: 0
  Digest: 0
  Digest::MD5: 0
  Digest::SHA: 0
  Dist::CheckConflicts: 0
  Email::Address: 0
  Email::Date::Format: 0
  Email::MIME::ContentType: 0
  Email::MIME::Encodings: 0
  Email::MIME::Header: 0
  Email::MessageID: 0
  Email::Simple::Creator: 0
  Encode: 0
  Encode::Locale: 0
  Env: 0
  Eval::Closure: 0
  Exception::Class: 0
  Exporter: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Config: 0
  ExtUtils::Constant: 0
  ExtUtils::Depends: 0
  ExtUtils::Helpers: 0
  ExtUtils::Install: 0
  ExtUtils::InstallPaths: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::MakeMaker::CPANfile: 0
  ExtUtils::Manifest: 0
  ExtUtils::ParseXS: 0
  ExtUtils::PkgConfig: 0
  ExtUtils::Typemaps: 0
  FCGI: 0
  File::BaseDir: 0
  File::DesktopEntry: 0
  File::Find::Iterator: 0
  File::Find::Object: 0
  File::Find::Object::Rule: 0
  File::Find::Rule: 0
  File::Find::Rule::Perl: 0
  File::Find::Rule::VCS: 0
  File::HomeDir: 0
  File::Listing: 0
  File::MMagic: 0
  File::MimeInfo: 0
  File::Path: 0
  File::ReadBackwards: 0
  File::Remove: 0
  File::ShareDir: 0
  File::ShareDir::Install: 0
  File::ShareDir::ProjectDistDir: 0
  File::Slurp: 0
  File::Slurp::Tiny: 0
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
  Filter::Util::Call: 0
  FreezeThaw: 0
  Getopt::Long: 0
  HTML::Form: 0
  HTML::Parser: 0
  HTML::Tagset: 0
  HTML::TokeParser: 0
  HTML::TreeBuilder: 0
  HTTP::Cookies: 0
  HTTP::Daemon: 0
  HTTP::Date: 0
  HTTP::Negotiate: 0
  HTTP::Response: 0
  HTTP::Response::Encoding: 0
  HTTP::Server::Simple: 0
  HTTP::Status: 0
  Hook::LexWrap: 0
  IO::All: 0
  IO::Capture: 0
  IO::HTML: 0
  IO::Handle: 0
  IO::Pty: 0
  IO::Seekable: 0
  IO::Socket::IP: 0
  IO::Socket::SSL: 0
  IO::String: 0
  IO::Zlib: 0
  IPC::Cmd: 0
  IPC::Run: 0
  IPC::Run3: 0
  IPC::System::Simple: 0
  JSON: 0
  JSON::PP: 0
  JSON::XS: 0
  LWP: 0
  LWP::MediaTypes: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Lingua::EN::Inflect: 0
  Lingua::EN::Numbers: 0
  List::MoreUtils: 0
  Locale::Maketext: 0
  Locale::Maketext::Lexicon: 0
  Locale::Maketext::Simple: 0
  Locale::TextDomain: 0
  Log::Agent: 0
  MIME::Base64: 0
  MIME::Types: 0
  MRO::Compat: 0
  Math::BigInt: 0
  Math::BigRat: 0
  Method::Signatures::Simple: 0
  Mixin::Linewise::Readers: 0
  Module::Build: 0
  Module::Build::Tiny: 0
  Module::CPANTS::Analyse: 0
  Module::CPANTS::Kwalitee: 0
  Module::CPANfile: 0
  Module::CoreList: 0
  Module::ExtractUse: 0
  Module::Find: 0
  Module::Implementation: 0
  Module::Load: 0
  Module::Load::Conditional: 0
  Module::Manifest: 0
  Module::Metadata: 0
  Module::Pluggable: 0
  Module::Runtime: 0
  Module::Signature: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  Mozilla::CA: 0
  Net::FTP: 0
  Net::HTTP: 0
  Net::HTTPS: 0
  Net::SSLeay: 0
  Number::Compare: 0
  PAR::Dist: 0
  PPI: 0
  PPIx::Regexp: 0
  PPIx::Utilities::Statement: 0
  Package::DeprecationManager: 0
  Package::Stash: 0
  Package::Stash::XS: 0
  Params::Check: 0
  Params::Util: 0
  Params::Validate: 0
  Parse::CPAN::Meta: 0
  Parse::RecDescent: 0
  Path::Class::File: 0
  Path::FindDev: 0
  Path::IsDev: 0
  Path::Tiny: 0
  Perl::Critic: 0
  Perl::MinimumVersion: 0
  Perl::OSType: 0
  Perl::Tidy: 0
  PerlIO::utf8_strict: 0
  Pod::Checker: 0
  Pod::Coverage: 0
  Pod::Coverage::TrustPod: 0
  Pod::Escapes: 0
  Pod::Eventual: 0
  Pod::Eventual::Simple: 0
  Pod::Man: 0
  Pod::Parser: 0
  Pod::Simple: 0
  Pod::Spell: 0
  Pod::Usage: 0
  Pod::Wordlist::hanekomu: 0
  Probe::Perl: 0
  Readonly: 0
  Role::Tiny: 0
  Scalar::Util: 0
  Set::Scalar: 0
  Socket: 0
  Software::License: 0
  Storable: 0
  String::Format: 0
  Sub::Exporter: 0
  Sub::Exporter::Progressive: 0
  Sub::Install: 0
  Sub::Name: 0
  Sub::Uplevel: 0
  TAP::Harness::Env: 0
  Task::Weaken: 0
  Term::ANSIColor: 0
  Test: 0
  Test::CPAN::Changes: 0
  Test::CPAN::Meta: 0
  Test::CPAN::Meta::JSON: 0
  Test::Deep: 0
  Test::DistManifest: 0
  Test::Distribution: 0
  Test::EOL: 0
  Test::Exception: 0
  Test::FailWarnings: 0
  Test::Fatal: 0
  Test::Harness: 0
  Test::Harness::Straps: 0
  Test::Kwalitee: 0
  Test::LeakTrace: 0
  Test::Manifest: 0
  Test::MinimumVersion: 0
  Test::Mojibake: 0
  Test::More: 0
  Test::NoTabs: 0
  Test::NoWarnings: 0
  Test::Object: 0
  Test::Output: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Pod::LinkCheck: 0
  Test::Portability::Files: 0
  Test::Requires: 0
  Test::Run: 0
  Test::Script: 0
  Test::Signature: 0
  Test::Spelling: 0
  Test::SubCalls: 0
  Test::Synopsis: 0
  Test::Tester: 0
  Test::TrailingSpace: 0
  Test::Trap: 0
  Test::UseAllModules: 0
  Test::Vars: 0
  Test::Version: 0
  Test::Warn: 0
  Test::Warnings: 0
  Text::Abbrev: 0
  Text::Aligner: 0
  Text::Autoformat: 0
  Text::Balanced: 0
  Text::Diff: 0
  Text::Glob: 0
  Text::ParseWords: 0
  Text::Reform: 0
  Text::Sprintf::Named: 0
  Text::Table: 0
  Text::Template: 0
  Text::Wrap: 0
  Thread::Queue: 0
  Thread::Semaphore: 0
  Time::HiRes: 0
  Time::Local: 0
  Tree::DAG_Node: 0
  Try::Tiny: 0
  Types::Serialiser: 0
  UNIVERSAL::isa: 0
  UNIVERSAL::require: 0
  URI: 0
  Unicode::CheckUTF8: 0
  Unicode::UTF8: 0
  Version::Requirements: 0
  WWW::Mechanize: 0
  WWW::RobotRules: 0
  XML::Parser: 0
  XSLoader: 0
  YAML: 0
  YAML::Any: 0
  YAML::Tiny: 0
  YAML::XS: 0
  base: 0
  bigint: 0
  common::sense: 0
  constant: 0
  constant::defer: 0
  if: 0
  lib: 0
  namespace::autoclean: 0
  namespace::clean: 0
  parent: 0
  perl: '5.005'
  threads: 0
  threads::shared: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
