---
abstract: 'Perl extension to install WWW::Mechanize'
author:
  - 'Kevin W. Henwood, <Khen1950fx@aol.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Mechanistic
no_index:
  directory:
    - inc
    - t
requires:
  CGI: 0
  CPAN::Meta: 0
  CPAN::Meta::Requirements: 0
  CPAN::Meta::YAML: 0
  Carp: 0
  Compress::Raw::Bzip2: 0
  Compress::Raw::Zlib: 0
  Crypt::SSLeay: 0
  Data::Dump: 0
  Data::Dumper: 0
  Digest::MD5: 0
  Digest::base: 0
  Encode: 0
  Encode::Locale: 0
  Exporter: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Install: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 0
  ExtUtils::ParseXS: 0
  ExtUtils::Typemaps: 0
  File::Compare: 0
  File::Listing: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  Getopt::Long: 0
  HTML::Form: 0
  HTML::Parser: 0
  HTML::Tagset: 0
  HTML::TreeBuilder: 0
  HTTP::Cookies: 0
  HTTP::Daemon: 0
  HTTP::Date: 0
  HTTP::Negotiate: 0
  HTTP::Request: 0
  HTTP::Server::Simple: 0
  IO::Compress::Gzip: 0
  IO::Dir: 0
  IO::Socket: 0
  IO::Socket::SSL: 0
  IO::Uncompress::Inflate: 0
  IPC::Cmd: 0
  JSON::PP: 0
  LWP::MediaTypes: 0
  LWP::Protocol: 0
  LWP::Protocol::http: 0
  LWP::Protocol::https: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  Locale::Maketext: 0
  Locale::Maketext::Lexicon: 0
  Locale::Maketext::Simple: 0
  MIME::Base64: 0
  Module::Build: 0
  Module::CoreList: 0
  Module::Load: 0
  Module::Load::Conditional: 0
  Module::Metadata: 0
  Module::Signature: 0
  Net::FTP: 0
  Net::HTTP: 0
  Net::SSLeay: 0
  PPI: 0
  Params::Check: 0
  Parse::CPAN::Meta: 0
  Perl::OSType: 0
  Pod::Coverage: 0
  Pod::Coverage::TrustPod: 0
  Pod::Escapes: 0
  Pod::Man: 0
  Pod::Simple: 0
  Pod::Spell: 0
  Pod::Usage: 0
  Pod::Wordlist::hanekomu: 0
  Scalar::Util: 0
  Socket: 0
  Sub::Uplevel: 0
  Term::ANSIColor: 0
  Test: 0
  Test::Builder::Tester: 0
  Test::CPAN::Meta: 0
  Test::Distribution: 0
  Test::Exception: 0
  Test::Fatal: 0
  Test::Harness: 0
  Test::LeakTrace: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Portability::Files: 0
  Test::Requires: 0
  Test::Script: 0
  Test::Signature: 0
  Test::Spelling: 0
  Test::Version: 0
  Test::Warn: 0
  Text::ParseWords: 0
  Text::Wrap: 0
  Time::HiRes: 0
  Time::Local: 0
  Tree::DAG_Node: 0
  Try::Tiny: 0
  URI::URL: 0
  Version::Requirements: 0
  WWW::Mechanize: 0
  WWW::RobotRules: 0
  XSLoader: 0
  YAML: 0
  base: 0
  constant: 0
  lib: 0
  perl: 5.005
  threads: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
